#!/bin/bash

# APIテスト結果レポート生成スクリプト
# テスト実行結果をHTMLレポートとして生成

set -e

echo "📊 APIテストレポート生成開始"
echo "=================================="

# 環境変数チェック
if [ -z "$API_URL" ]; then
    echo "⚠️  警告: API_URL環境変数が設定されていません"
    export API_URL="https://u4v31lnz5m.execute-api.ap-northeast-1.amazonaws.com/prod"
fi

echo "📍 テスト対象API: $API_URL"
echo ""

# レポートディレクトリを作成
REPORT_DIR="test-reports"
mkdir -p "$REPORT_DIR"

# タイムスタンプ
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
REPORT_FILE="$REPORT_DIR/api-test-report-$TIMESTAMP.html"

echo "📝 レポート生成中..."

# HTMLレポートでテスト実行
npx playwright test --config=test/playwright-api.config.ts test/e2e/*.api.spec.ts --reporter=html --output-dir="$REPORT_DIR/playwright-report-$TIMESTAMP"

# カスタムレポート生成
cat > "$REPORT_FILE" << EOF
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>APIテストレポート - $TIMESTAMP</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        .header { background: #f0f8ff; padding: 20px; border-radius: 8px; margin-bottom: 20px; }
        .section { margin: 20px 0; padding: 15px; border: 1px solid #ddd; border-radius: 5px; }
        .success { background: #d4edda; border-color: #c3e6cb; }
        .warning { background: #fff3cd; border-color: #ffeaa7; }
        .error { background: #f8d7da; border-color: #f5c6cb; }
        .code { background: #f8f9fa; padding: 10px; border-radius: 4px; font-family: monospace; }
        table { width: 100%; border-collapse: collapse; margin: 10px 0; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background: #f2f2f2; }
    </style>
</head>
<body>
    <div class="header">
        <h1>🧪 APIテストレポート</h1>
        <p><strong>生成日時:</strong> $(date)</p>
        <p><strong>テスト対象API:</strong> $API_URL</p>
    </div>

    <div class="section">
        <h2>📋 テスト概要</h2>
        <table>
            <tr><th>テストカテゴリ</th><th>説明</th><th>ファイル</th></tr>
            <tr><td>基本API検証</td><td>画像合成APIの基本機能テスト</td><td>api-validation.api.spec.ts</td></tr>
            <tr><td>アップロードAPI基本</td><td>S3アップロード機能の基本テスト</td><td>upload-api-validation.api.spec.ts</td></tr>
            <tr><td>包括的アップロード</td><td>アップロード機能の詳細テスト</td><td>upload-comprehensive.api.spec.ts</td></tr>
        </table>
    </div>

    <div class="section">
        <h2>🔗 詳細レポート</h2>
        <p>詳細なテスト結果は以下のPlaywrightレポートをご確認ください：</p>
        <div class="code">
            <a href="./playwright-report-$TIMESTAMP/index.html" target="_blank">
                Playwrightレポートを開く
            </a>
        </div>
    </div>

    <div class="section">
        <h2>🚀 実行コマンド</h2>
        <div class="code">
# 全APIテスト実行<br>
npm run test:api-all<br><br>

# 個別テスト実行<br>
npm run test:api-validation<br>
npm run test:upload-api<br>
npm run test:upload-comprehensive<br><br>

# 正解画像更新<br>
npm run update-test-assets
        </div>
    </div>

    <div class="section">
        <h2>📚 関連ドキュメント</h2>
        <ul>
            <li><a href="../docs/api-testing-guide.md">APIテストガイド</a></li>
            <li><a href="../test/test-assets/README.md">テストアセット説明</a></li>
            <li><a href="../README.md">プロジェクト概要</a></li>
        </ul>
    </div>

    <div class="section">
        <h2>🔧 トラブルシューティング</h2>
        <div class="warning">
            <h3>よくある問題</h3>
            <ul>
                <li><strong>API_URL未設定:</strong> 環境変数API_URLを設定してください</li>
                <li><strong>正解画像不足:</strong> <code>npm run update-test-assets</code> を実行</li>
                <li><strong>タイムアウト:</strong> <code>PLAYWRIGHT_TIMEOUT=30000</code> を設定</li>
            </ul>
        </div>
    </div>

    <footer style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; color: #666;">
        <p>Generated by Image Composition API Test Suite - $TIMESTAMP</p>
    </footer>
</body>
</html>
EOF

echo "✅ レポート生成完了！"
echo ""
echo "📄 生成されたファイル:"
echo "   - HTMLレポート: $REPORT_FILE"
echo "   - Playwrightレポート: $REPORT_DIR/playwright-report-$TIMESTAMP/"
echo ""
echo "🌐 レポートを開く:"
echo "   open $REPORT_FILE"